#!/usr/bin/env bash
# tests/install-render-stable.test.sh
#
# Closes the "PR author forgot to re-render install.sh" class of bug that
# check-drift.sh only catches post-merge from the operator's live config.
# The gate verifies the render pipeline is intact end-to-end:
# 0. Every active-template @@VAR@@ placeholder is well-formed (no digits —
# install.sh's substitution regex would silently skip them) AND is a
# key in tests/fixtures/ci.local.env (the fixture is provably complete,
# not just "complete enough that ambient CI env vars masked the gap").
# 1. install.sh --build-only exits 0 for the claude harness
# 2. install.sh --build-only exits 0 for the codex harness
# 3. Re-render is byte-deterministic: two consecutive runs with the same
# fixture local.env produce identical manifest hashes.
#
# Assertion 0 (added Codex pre-PR review F1+F2) closes two gaps in
# the build-only path that would otherwise leak through assertions 1+2:
# - F1 ambient-env masking: install.sh resolves @@VAR@@ via `${!VAR:-}`,
# so a new placeholder like @@CI@@, @@HOME@@, @@GITHUB_WORKSPACE@@, or
# @@RUNNER_OS@@ would be silently satisfied by GitHub Actions' own env
# vars even with the fixture un-updated. The fixture-completeness check
# reads the FIXTURE file (not the live env) so ambient-env vars cannot
# mask a missing entry.
# - F2 regex-mismatch: install.sh's placeholder gate uses [A-Z_]+ — a
# template token containing digits (@@VAR2@@, @@QUE80_FOO@@) would
# neither be substituted nor flagged by the empty-placeholder check.
# Assertion 0's well-formedness check refuses to be silent about a
# template token install.sh's narrow regex cannot see.
#
# Mirrored by.github/workflows/install-render-stable.yml — CI sources the
# same test via `bash tests/run.sh`, so local pre-push reproduction is
# byte-identical to the CI gate.

# --- Per-run tmp dir; cleaned at end of file. -----------------------------
IRS_DIR="$(mktemp -d)"
IRS_CLAUDE_TGT="$IRS_DIR/claude"
IRS_CODEX_TGT="$IRS_DIR/codex"
IRS_ENV_CLAUDE="$IRS_DIR/claude.local.env"
IRS_ENV_CODEX="$IRS_DIR/codex.local.env"

# Build per-harness local.env files from the SHIPPED CI fixture, overriding
# CLAUDE_CONFIG_DIR / CODEX_HOME to the per-run tmp target. This proves the
# fixture's NON-target vars (OBSIDIAN_VAULT_PATH) are the canonical source
# for both CI and the local test — same file, same values. The target
# override is mechanical isolation only. (: CODEGRAPH_BINARY dropped
# from fixture along with codegraph framework integration.)
IRS_CI_FIXTURE="$REPO_ROOT/tests/fixtures/ci.local.env"

# --- Assertion 0: fixture is provably complete vs active templates --------
# Scans every active entrypoint template + hook script for @@VAR@@ tokens,
# then verifies each non-special token is (a) well-formed under install.sh's
# substitution regex (install.sh:227 — uppercase + underscore only, no
# digits — see header F2 commentary) AND (b) a key in tests/fixtures/
# ci.local.env. install.sh is NOT invoked here — we scan the FIXTURE FILE
# directly so ambient CI env vars cannot mask a missing fixture entry
# (header F1 commentary).
#
# Special tokens not requiring fixture entries:
# - CAPABILITY_CATALOG — internally generated by install.sh, not env-sourced
# - OPERATOR_SKILLS_OVERLAY — injection marker; install.{sh,ps1} splice
# the operator overlay file (SKILLS_OVERLAY_PATH) at it, or empty for a
# spine-only render. It is consumed before the @@VAR@@ loop, so it is never a
# fixture-keyed path var. SKILLS_OVERLAY_PATH itself is optional and operator-
# local (absent in CI → spine-only render), so it is deliberately NOT in the
# fixture; asserting it here would force a non-existent CI overlay file.
#
# Per-harness build-target vars (CLAUDE_CONFIG_DIR, CODEX_HOME) ARE required
# to be in the fixture even though the test overrides them per-run — the
# fixture is also operator-facing documentation of the contract.
irs_special_tokens="CAPABILITY_CATALOG OPERATOR_SKILLS_OVERLAY"

# Active template + hook surfaces install.sh's compile_entrypoint / install_hook
# substitute. Symmetric across harnesses by design (claude + codex parity).
irs_active_surfaces=(
  "$REPO_ROOT/harnesses/claude/CLAUDE.template.md"
  "$REPO_ROOT/harnesses/claude/SKILLS.template.md"
  "$REPO_ROOT/harnesses/codex/AGENTS.template.md"
  "$REPO_ROOT/harnesses/claude/hooks/framework-surface.sh"
  "$REPO_ROOT/harnesses/codex/hooks/framework-surface.sh"
)

# Wider scan pattern than install.sh's [A-Z_]+ — catches F2 digit-containing
# tokens install.sh would silently skip. install.sh's narrow gate is the
# bug; assertion 0 names it at PR time.
irs_token_re='@@[A-Z_][A-Z0-9_]*@@'

# Enumerate tokens (sorted unique) across all active surfaces.
irs_all_tokens="$(grep -oEh "$irs_token_re" "${irs_active_surfaces[@]}" 2>/dev/null \
  | sort -u || true)"

# Fixture keys: lines matching ^VAR= ignoring blanks/comments.
irs_fixture_keys="$(grep -E '^[A-Z_][A-Z0-9_]*=' "$IRS_CI_FIXTURE" \
  | sed -E 's/=.*//' | sort -u || true)"

irs_completeness_fail=0
irs_completeness_msgs=""
while IFS= read -r irs_tok; do
  [ -n "$irs_tok" ] || continue
  # Strip @@ delimiters.
  irs_var="${irs_tok#@@}"; irs_var="${irs_var%@@}"
  # Skip the special internally-generated tokens (CAPABILITY_CATALOG).
  case " $irs_special_tokens " in *" $irs_var "*) continue ;; esac

  # F2 well-formedness: install.sh's regex is [A-Z_]+ (NO digits). Reject any
  # token containing a digit — install.sh would silently skip substitution
  # AND not flag it as unresolved.
  if printf '%s\n' "$irs_var" | grep -qE '[0-9]'; then
    irs_completeness_fail=1
    irs_completeness_msgs+="placeholder $irs_tok contains a digit — install.sh's substitution regex [A-Z_]+ would silently skip it (F2)"$'\n'
    continue
  fi

  # F1 completeness: fixture must declare this token as a key.
  if ! printf '%s\n' "$irs_fixture_keys" | grep -qxF "$irs_var"; then
    irs_completeness_fail=1
    irs_completeness_msgs+="placeholder $irs_tok present in active templates/hooks but missing from tests/fixtures/ci.local.env (F1: ambient CI env vars must not be relied on)"$'\n'
  fi
done <<< "$irs_all_tokens"

if [ "$irs_completeness_fail" -eq 0 ]; then
  _pass "fixture covers every active-template @@VAR@@ (F1+F2)"
else
  _fail "fixture covers every active-template @@VAR@@ (F1+F2)" \
    "$(printf '%s' "$irs_completeness_msgs" | head -20)"
fi


# Claude env: fixture content + per-run CLAUDE_CONFIG_DIR override appended
# last (later assignment wins when install.sh sources the file).
{
  cat "$IRS_CI_FIXTURE"
  printf '\nCLAUDE_CONFIG_DIR=%q\n' "$IRS_CLAUDE_TGT"
} > "$IRS_ENV_CLAUDE"

# Codex env: same shape, per-run CODEX_HOME override.
{
  cat "$IRS_CI_FIXTURE"
  printf '\nCODEX_HOME=%q\n' "$IRS_CODEX_TGT"
} > "$IRS_ENV_CODEX"

# --- Assertion 1: claude harness build is green ----------------------------
# install.sh --build-only validates the build and prints the temp build path
# to stdout. Exit 0 means: every @@VAR@@ in active claude templates resolved
# from the fixture, no unresolved placeholders, valid settings.json,
# skills/ dir produced. This is the PR-time gate.
irs_claude_status=0
irs_claude_out="$(AI_CONFIG_LOCAL_ENV="$IRS_ENV_CLAUDE" \
  bash "$REPO_ROOT/scripts/install.sh" --harness claude --build-only 2>&1)" \
  || irs_claude_status=$?
assert_eq "install.sh --harness claude --build-only exits 0 with CI fixture" \
  "0" "$irs_claude_status"
if [ "$irs_claude_status" -ne 0 ]; then
  printf '       install.sh output:\n%s\n' "$irs_claude_out" >&2
fi

# --- Assertion 2: codex harness build is green -----------------------------
# Symmetric to assertion 1 — codex's AGENTS.template.md uses the same
# @@OBSIDIAN_VAULT_PATH@@ placeholder, and its hook scripts use
# @@AI_CONFIG_DIR@@. A new codex-specific placeholder added without a
# fixture entry trips here at PR time.
irs_codex_status=0
irs_codex_out="$(AI_CONFIG_LOCAL_ENV="$IRS_ENV_CODEX" \
  bash "$REPO_ROOT/scripts/install.sh" --harness codex --build-only 2>&1)" \
  || irs_codex_status=$?
assert_eq "install.sh --harness codex --build-only exits 0 with CI fixture" \
  "0" "$irs_codex_status"
if [ "$irs_codex_status" -ne 0 ]; then
  printf '       install.sh output:\n%s\n' "$irs_codex_out" >&2
fi

# --- Assertion 3: re-render is byte-deterministic --------------------------
# install.sh promises deterministic builds (jq -S sorts manifest keys; no
# timestamps in the manifest; generate_capability_catalog LC_ALL=C sort).
# Pin that promise: two consecutive --build-only runs against the SAME
# target must produce byte-identical.build-manifest.json content. Breaks if
# any future change to the build pipeline reintroduces a timestamp, an
# environment-leaking value, or any non-deterministic enumeration.
#
# The runs MUST share the same CLAUDE_CONFIG_DIR target: generate_settings
# substitutes the absolute $TARGET path into hook `command` fields in
# settings.json, and write_manifest hashes the generated settings.json. Two
# builds against different targets would produce different settings.json
# bytes and therefore different manifests — that's expected behavior, not a
# determinism violation. Same target + same source + same env-vars = same
# manifest, every time. (The temp BUILD subdir under the target has a random
# mktemp suffix; comparison is across two SEPARATE build subdirs both rooted
# at the same TARGET.)
IRS_DET_TGT="$IRS_DIR/det_shared"
IRS_ENV_DET="$IRS_DIR/det.local.env"
{ cat "$IRS_CI_FIXTURE"; printf '\nCLAUDE_CONFIG_DIR=%q\n' "$IRS_DET_TGT"; } > "$IRS_ENV_DET"

irs_det_a="$(AI_CONFIG_LOCAL_ENV="$IRS_ENV_DET" \
  bash "$REPO_ROOT/scripts/install.sh" --harness claude --build-only 2>/dev/null)"
irs_det_b="$(AI_CONFIG_LOCAL_ENV="$IRS_ENV_DET" \
  bash "$REPO_ROOT/scripts/install.sh" --harness claude --build-only 2>/dev/null)"

if [ -n "$irs_det_a" ] && [ -n "$irs_det_b" ] \
   && [ -f "$irs_det_a/.build-manifest.json" ] \
   && [ -f "$irs_det_b/.build-manifest.json" ]; then
  # Portable sha256 — match the pattern install.sh + check-drift.sh use.
  if command -v sha256sum >/dev/null 2>&1; then
    irs_hash_a="$(sha256sum "$irs_det_a/.build-manifest.json" | cut -d' ' -f1)"
    irs_hash_b="$(sha256sum "$irs_det_b/.build-manifest.json" | cut -d' ' -f1)"
  else
    irs_hash_a="$(shasum -a 256 "$irs_det_a/.build-manifest.json" | cut -d' ' -f1)"
    irs_hash_b="$(shasum -a 256 "$irs_det_b/.build-manifest.json" | cut -d' ' -f1)"
  fi
  assert_eq "build manifest is byte-deterministic across re-renders" \
    "$irs_hash_a" "$irs_hash_b"
  if [ "$irs_hash_a" != "$irs_hash_b" ]; then
    printf '       manifest A: %s\n' "$irs_det_a/.build-manifest.json" >&2
    printf '       manifest B: %s\n' "$irs_det_b/.build-manifest.json" >&2
    printf '       diff (truncated to 30 lines):\n' >&2
    diff "$irs_det_a/.build-manifest.json" "$irs_det_b/.build-manifest.json" \
      | head -30 >&2
  fi
  # Clean up the inspect-only build dirs install.sh leaves behind under
  # --build-only (trap disabled to preserve for inspection).
  rm -rf "$irs_det_a" "$irs_det_b"
else
  _fail "determinism assertion could not run (one or both builds failed)" \
    "build A path: [$irs_det_a]" "build B path: [$irs_det_b]"
fi

rm -rf "$IRS_DIR"
